### ISSUE TITLE
cid填什么?

### ISSUE THREAD

**Issue by ghost** [huiqiangyang/jhipster-docker-compose#3]
➜  ~ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Running   tcp://192.168.99.100:2376           v17.03.0-ce

那我这里 cid应该填 default .第二个参数默认 jhipster

**Comment by ghost** [comment]
➜  jhipster-docker-compose git:(master) docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                    PORTS                                                                                                                                                                           NAMES
72ade226087f        jhipster/jhipster:v4.1.1   "tail -f /home/jhi..."   43 seconds ago      Up 42 seconds             0.0.0.0:32774->3001/tcp, 0.0.0.0:32773->8080/tcp, 0.0.0.0:32772->8081/tcp, 0.0.0.0:32771->8082/tcp, 0.0.0.0:32770->8083/tcp, 0.0.0.0:32769->9000/tcp, 0.0.0.0:32768->9999/tcp   jhipsterdockercompose_jhipster_1
1d8c1725b945        mysql:5.7.13               "docker-entrypoint..."   4 days ago          Exited (255) 4 days ago   0.0.0.0:3306->3306/tcp                                                                                                                                                          docker_jhipstersampleapplication-mysql_1
3b190abec139        jenkins                    "/bin/tini -- /usr..."   4 days ago          Exited (255) 4 days ago   50000/tcp, 0.0.0.0:49001->8080/tcp                                                                                                                                              myjenkins

**Comment by huiqiangyang** [comment]
cid 是执行 `docker ps -a`  之后显示出来的容器Id, 完整的执行命令是 `docker exec -it cid bach`
或者直接执行 `docker exec -it jhipster bach`

**Comment by huiqiangyang** [comment]
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
72ade226087f jhipster/jhipster:v4.1.1 "tail -f /home/jhi..." 43 seconds ago Up 42 seconds 0.0.0.0:32774->3001/tcp, 0.0.0.0:32773->8080/tcp, 0.0.0.0:32772->8081/tcp, 0.0.0.0:32771->8082/tcp, 0.0.0.0:32770->8083/tcp, 0.0.0.0:32769->9000/tcp, 0.0.0.0:32768->9999/tcp jhipsterdockercompose_jhipster_1


上面的容器Id 是：72ade226087f

**Comment by ghost** [comment]
➜  jhipster-docker-compose git:(master) docker exec -it 72ade226087f jhipster batch
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"jhipster\": executable file not found in $PATH"
